export const FETCH_NOTES_START = 'FETCH_NOTES_START';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR';

export const LOAD_NOTE_START = 'LOAD_NOTE_START';
export const LOAD_NOTE_SUCCESS = 'LOAD_NOTE_SUCCESS';
export const LOAD_NOTE_ERROR = 'LOAD_NOTE_ERROR';

export const SEND_NOTE_START = 'SEND_NOTE_START';
export const SEND_NOTE_SUCCESS = 'SEND_NOTE_SUCCESS';
export const SEND_NOTE_ERROR = 'SEND_NOTE_ERROR';

export const EDIT_NOTE_START = 'EDIT_NOTE_START';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR';

export const DELETE_NOTE = 'DELETE_NOTE';